[HOTFIX-1914][BUG-112405] fix ingestion entities with nulls (#198)
What changes were proposed in this pull request?

Give the ability to ingest entities which contain null values.

How was this patch tested?

I create the unit test which was failing before fix with such exception:
java.lang.UnsupportedOperationException: PrimitiveType coder: unsupported data type null

Fix simple omit the null values and didn't try to save it (which is correct, HBase didn't store null)

* fix ingestion entities with nulls

* Suggested changes in review

* reorganizing test structure

* add possibility to define catalog in tests

* Minor format change

Change-Id: I79b4553900438354bf76febcf5e97873c6b16670